### ISSUE TITLE
Why the result I have executed using 3D example code is not the same with the example result?

### ISSUE THREAD

**Issue by fenfam** [SamPIngram/RipleyK#2]
[-9.290137551123609e-06, -0.00010544767161566743, -0.00039142698870800463, -0.0007282757869681578, -0.0013863220751694216, -0.002301632731796177, -0.002895761209242842, -0.004294205083374969, -0.005929855937486295, -0.007915443959695345]
![image](https://user-images.githubusercontent.com/30427210/118471214-15ffbd80-b73a-11eb-823b-153d4581ac18.png)

**Comment by SamPIngram** [comment]
Hi @fenfam thanks for pointing this out. This was an error in the README examples, not the code. Your results here are correct. The issue was that back in the commit (e6668488ab3d623afb663058b85a8b15959865d6) I spotted that the calculations were included the point being analysed as within proximity to itself. Which was not as intended I fixed the code but didn't update the README results. 

I've updated the README so thanks for that. Commit 9820dfd711b52fcd4a545da59584c2f6f5788ce3
