### ISSUE TITLE
Understanding inputs (bounding radius?) and outputs

### ISSUE THREAD

**Issue by ViriatoII** [SamPIngram/RipleyK#3]
Hi,

Your function seems very useful. I'm not sure I understand the difference between radius and bounding radius.

I think the radius is the distance around each point where I want to measure K. Bounding radius seems to be the radius of the study area, used for spatial randomness assumptions? (Not having a perfect circular area, I'm using the maximum axis distance between two observations) 

Here's a small example of how I'm applying your function and how my data is:

```
import ripleyk

# p1 is list of coordinate pairs
print(p1[2:7])
xs = np.array([i[0] for i in p1])
ys = np.array([i[1] for i in p1])

print(f"Xrange is: {max(xs) - min(xs)}")
print(f"Yrange is: {max(ys) - min(ys)}")

radius = [10,20]
bounding_radius = 150

k = ripleyk.calculate_ripley(radius, bounding_radius, d1=xs, d2=ys, CSR_Normalise=True)

k
```

Result:

> [(56, 113), (43, 106), (41, 117), (67, 59)]
> Xrange is: 90
> Yrange is: 146
> [2827.433388230814, 10040.27366432983]

So the output is the K value corresponding to each radius in the input.  Do you have an implementation of p-value calculation (or rough estimation)? This very interesting paper minimizes Monte Carlo simulations for p-val estimation by having a model of point distribution that accounts for intensity and study area size.

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0080914

Cheers,
Ricardo

**Comment by SamPIngram** [comment]
Hi Ricardo,

Thanks for taking a look at the project. You are correct in how you have defined the radius and bounding radius. The last piece to add is why you would want to add a bounding radius. This should only get used if you boundary_correct=True, in your example it looks like you do not have this. The reason you would want to correct the boundary of your study area is that for a point located towards the edge of the study area, where radius now extends outside the area other points could be placed, it will negatively bias the values for them. 

The function here is how that is calculated and addressed when using boundary correction:
https://github.com/SamPIngram/RipleyK/blob/9820dfd711b52fcd4a545da59584c2f6f5788ce3/ripleyk/ripleyk.py#L17

However, if your study area is not spherical you will have trouble using this function as it was designed for spherical study areas. In my own work, I have done this for none spherical study areas through the use of Monte Carlo to approximate volume overlaps which may be of use if you want to account for the boundary.

In terms of the P-value, I do not have an implementation where this is calculated. However, that might be a useful feature to add. At this current time, I would not be able to add this for a while due to other commitments. However, if you do figure it out you are more than welcome to submit the change for implementation. 

Hope this helps,
Sam

**Comment by ViriatoII** [comment]
Very fast and complete answer, thanks! One last small question then:

Running without bounding_radius gives an error asking for the sample_size parameter. What is this? I thought NUM of points   (would be redundant that the function asks for it when it can derive it from d1/d2/d3) but now I see that it is used to calculate a bound_size and it looks like a radius :

`bound_size = np.pi * sample_size**2`

I have decided to just go for Monte Carlo Simulations. I found a very nice [package ](https://github.com/pysal/pointpats/blob/master/pointpats/ripley.py) that does this, but they don't work with z coordinates and also not with custom study areas.

I'll close the issue in advance and thank you,
Ricardo
